title: samuelsoderberg.se

url: https://www.samuelsoderberg.se
picture: assets/images/picture.jpg

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
